//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace szakszerviz
{
    using System;
    using System.Collections.Generic;
    
    public partial class szerviz
    {
        public int Id { get; set; }
        public string rendszam { get; set; }
        public string marka { get; set; }
        public string tipus { get; set; }
        public System.DateTime forgalomban { get; set; }
        public int fk_szolgaltatas_id { get; set; }
        public System.DateTime felvetel { get; set; }
    
        public virtual szolgaltatas szolgaltatas { get; set; }
    }
}
